### ISSUE TITLE
Lot of errors in Nuget package and plugin title

### ISSUE THREAD

**Issue by MscrmTools** [santoshCRM/Dynamics-CRM-personal-view-#1]
First, please change your nuget package to use your own logo (not mine) and author name (not mine, again)
Then, there is typo errors
![image](https://user-images.githubusercontent.com/10774317/27866313-1d0aa570-6196-11e7-800a-c210dd4bf929.png)

**Comment by santoshCRM** [comment]
Changes are done.

**Comment by MscrmTools** [comment]
Thanks!
