### ISSUE TITLE
No longer works with the latest version of XRMToolbox

### ISSUE THREAD

**Issue by simes1** [santoshCRM/Dynamics-CRM-personal-view-#3]
This plug-in no longer appears to work with the latest version of XRMToolbox:

https://github.com/MscrmTools/XrmToolBox/issues/868

**Comment by santoshCRM** [comment]
Plugin update and issue fixed now.

**Comment by simes1** [comment]
Thank - you.  I'm not working for a week but I'll give this a go when I'm back.
